# -*- coding: utf-8 -*-
"""File_conversion_mp3_to_wav.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lpjglvwfy4QDOrRMpn98gHgLIWv4b777

# **.mp3 to .wav file conversion**

**First we will install the necesary modules if not already present in our system**
"""

pip install pydub

pip install ffmpeg

"""**We then import the modules into our code**"""

import os
from pydub import AudioSegment
import os.path
import sys

"""**Here a function is created called 'file_conversion' where we pass two arguments, source path and the destination path, and we read the set of files from the path provided and convert them.**"""

def file_conversion(source, destination):
  # Get all .mp3 files present in the folder
  src = source.replace('\\', '/')
  dst = destination.replace('\\', '/')
  filelist = []
  for path, subdirs, files in os.walk(src):
    for file in files:
      if file.endswith('.mp3') or file.endswith('.MP3'):
        filelist.append(os.path.join(path, file))
  # Printing all the .mp3 files found in the source directory
  if len(filelist)==0:
    sys.exit("No .mp3 files found!!\nPlease check the directory")
  print(filelist)

  # Adding a check point to check if the destination folder is present or not. If not, creating it
  if not os.path.isdir(dst):
    os.mkdir(dst)
  
  # Change the working directory to the destination path
  os.chdir(dst)
  
  for files in filelist:
    name = (os.path.splitext(files)[0]).split('/')[-1]
    mp3_sound = AudioSegment.from_mp3(files)
    mp3_sound.export("{0}.wav".format(name), format="wav")

"""This is the main part where we call the function and send the parameters"""

# Taking the user input of the source and destination paths that we need to look into
src = input("Enter the source path of the MP3 files: ")
dst = input("Enter the destination where the conveter wav needs to be saved: ")
file_conversion(src, dst)

"""So the end result is that all the .mp3 files in the provided source path will be converted to .wav format and those files will be saved in the destination folder."""